(ns dns-big-d-site.core.subs
  (:require [re-frame.core :as rf]))

(rf/reg-sub :lang (fn [db _] (:lang db)))
(rf/reg-sub :booking-modal-open? (fn [db _] (:booking-modal-open? db)))
(rf/reg-sub :active-testimonial (fn [db _] (:active-testimonial db)))
(rf/reg-sub :login-modal-open? (fn [db _] (:login-modal-open? db)))
(rf/reg-sub :login-username (fn [db _] (:login-username db)))
(rf/reg-sub :login-password (fn [db _] (:login-password db)))
(rf/reg-sub :login-error (fn [db _] (:login-error db)))
(rf/reg-sub :auth-token (fn [db _] (:auth-token db)))
(rf/reg-sub :current-user (fn [db _] (:current-user db)))
(rf/reg-sub :is-logged-in? (fn [db _] (not (nil? (:auth-token db)))))
(rf/reg-sub :build-orders (fn [db _] (:build-orders db)))
(rf/reg-sub :selected-build-order (fn [db _] (:selected-build-order db)))
(rf/reg-sub :loading? (fn [db _] (:loading? db)))
(rf/reg-sub :upload-modal-open? (fn [db _] (:upload-modal-open? db)))
(rf/reg-sub :replay-uploading? (fn [db _] (:replay-uploading? db)))
(rf/reg-sub :upload-name (fn [db _] (:upload-name db "")))
(rf/reg-sub :upload-author (fn [db _] (:upload-author db "")))
(rf/reg-sub :upload-playstyle (fn [db _] (:upload-play-style db "")))
(rf/reg-sub :upload-strategic-goals (fn [db _] (:upload-strategic-goals db "")))
(rf/reg-sub :upload-counters (fn [db _] (:upload-counters db "")))
(rf/reg-sub :upload-weaknesses (fn [db _] (:upload-weaknesses db "")))
(rf/reg-sub :upload-transition-plan (fn [db _] (:upload-transition-plan db "")))
(rf/reg-sub :upload-youtube-url (fn [db _] (:upload-youtube-url db "")))
(rf/reg-sub :upload-error (fn [db _] (:upload-error db nil)))
(rf/reg-sub :delete-confirm (fn [db _] (:delete-confirm db nil)))
(rf/reg-sub :edit-bo-id (fn [db _] (:edit-bo-id db)))
(rf/reg-sub :current-route (fn [db _] (:current-route db)))
